"""
Django settings for ruhvz project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
try:
    from secrets import SECRET_KEY
except:
    SECRET_KEY = 'PLACEHOLDER'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

STATIC_ROOT = 'ruhvz/static'

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mptt',
    'geoposition',
    'ruhvz.users',
    'ruhvz.game'
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'ruhvz.urls'

WSGI_APPLICATION = 'ruhvz.wsgi.application'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

try:
    from secrets import DATABASES1
except:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

# Other dependencies

GEOPOSITION_MAP_OPTIONS = {
    'minZoom' : 5,
    'zoom' : 17,
    'maxZoom' : 18,
    'center' : { 'lat': -33.314236, 'lng': 26.518826},
}

GEOPOSITION_MARKER_OPTIONS = {
    'cursor': 'move',
    'position': { 'lat': -33.314236, 'lng': 26.5188267},
}

GAME_SW_BOUND = (-33.320192, 26.508758)
GAME_NE_BOUND = (-33.308830, 26.524041)

HUMAN_KILL_POINTS = 1

HVT_KILL_POINTS = 5
HVD_KILL_POINTS = 3

HVT_AWARD_POINTS = 3

SUIT_CONFIG = {
    #header
    'ADMIN_NAME': 'Hivemind',
    'HEADER_DATE_FORMAT': 'l, j. F Y',
    'HEADER_TIME_FORMAT': 'H:i',

    #forms
    'SHOW_REQUIRED_ASTERISK': True,
    'CONFIRM_UNSAVED_CHANGES': True,

    #menu
    'SEARCH_URL': '', #disable admin search
    'MENU_ICONS': {
        'sites': 'icon-leaf',
        'auth': 'icon-lock',
        'game': 'icon-star',
        'users': 'icon-user',
    },
    'MENU_OPEN_FIRST_CHILD': True,
    'MENU_EXPAND': ('auth.group'),
    'MENU': (
        'sites',
        {'app': 'auth', 'icon': 'icon-lock', 'models': ('user', 'group')},
        {'app': 'users', 'icon': 'icon-user', 'models': ('Profiles', )},
        {'app': 'game', 'icon': 'icon-envelope', 'models': ('Awards', 'Games', 'High value dorms', 'High value targets', 'Kills', 'New_ squads', 'Players', 'Squads')},
        {'label': 'Back to Site', 'icon': 'icon-leaf', 'url': '/'},
    ),

    #misc
    'LIST_PER_PAGE': 30
}